export const locationsData = {
    "kerala": [
        "alappuzha",
        "ernakulam",
        "idukki",
        "kannur",
        "kasaragod",
        "kollam",
        "kottayam",
        "kozhikode",
        "malappuram",
        "palakkad",
        "pathanamthitta",
        "thiruvananthapuram",
        "thrissur",
        "wayanad"
    ],
    "tamil nadu": [
        "ariyalur",
        "chengalpattu",
        "chennai",
        "coimbatore",
        "cuddalore",
        "dharmapuri",
        "dindigul",
        "erode",
        "kallakurichi",
        "kanchipuram",
        "kanyakumari",
        "karur",
        "krishnagiri",
        "madurai",
        "mayiladuthurai",
        "nagapattinam",
        "namakkal",
        "nilgiris",
        "perambalur",
        "pudukkottai",
        "ramanathapuram",
        "ranipet",
        "salem",
        "sivaganga",
        "tenkasi",
        "thanjavur",
        "theni",
        "thoothukudi",
        "tiruchirappalli",
        "tirunelveli",
        "tirupattur",
        "tiruppur",
        "tiruvallur",
        "tiruvannamalai",
        "tiruvarur",
        "vellore",
        "viluppuram",
        "virudhunagar"
    ],
    "karnataka": [
        "bagalkote",
        "ballari",
        "belagavi",
        "bengaluru rural",
        "bengaluru urban",
        "bidar",
        "chamarajanagara",
        "chikkaballapura",
        "chikkamagaluru",
        "chitradurga",
        "dakshina Kannada",
        "davanagere",
        "dharwad",
        "gadag",
        "hassan",
        "haveri",
        "kalaburagi",
        "kodagu",
        "kolar",
        "koppala",
        "mandya",
        "mysuru",
        "raichur",
        "ramanagara",
        "shivamogga",
        "tumakuru",
        "udupi",
        "uttara kannada",
        "vijayapura",
        "vijayanagara",
        "yadgir"
    ],
    "goa": [
        "north goa",
        "south goa"
    ]
};
